version: 2

references:
    cache_key: &cache_key
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "core/build.gradle" }}-{{ checksum  "data/build.gradle" }}

jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/android:api-29
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx3200m"
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key
      - run:
         name: Chmod permissions
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
